# Generated by Django 5.0.6 on 2024-10-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_author_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='award')),
                ('title', models.CharField(max_length=225)),
                ('sub_title', models.CharField(max_length=225)),
            ],
            options={
                'verbose_name': 'Award',
                'verbose_name_plural': 'Awards',
                'db_table': 'award',
            },
        ),
    ]
