# Generated by Django 5.0.6 on 2024-10-19 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_award'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='sub_title',
            new_name='award_name',
        ),
    ]
