# Generated by Django 5.0.6 on 2024-10-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_sub_title_award_award_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='is_home',
            field=models.BooleanField(default=False),
        ),
    ]
